export const GET_USER_ALBUM_LIST = 'GET_USER_ALBUM_LIST'
export const GET_USER_ALBUMS = 'GET_USER_ALBUMS'
export const GET_USER_ALBUMS_SUCCESS = 'GET_USER_ALBUMS_SUCCESS'
export const GET_USER_ALBUMS_ERROE = 'GET_USER_ALBUMS_ERROE'
